# Generated by Django 5.2 on 2025-04-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=6),
        ),
    ]
